//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeWebApiService
{
    using System;
    using System.Collections.Generic;
    
    public partial class ngEmployees
    {
        public string code { get; set; }
        public string name { get; set; }
        public string gender { get; set; }
        public Nullable<decimal> salary { get; set; }
        public string dateOfBirth { get; set; }
    }
}
