//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServicesAJAX.ServiceReferenceCountries {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Country", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Country : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryDescriptionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string CountryDescription {
            get {
                return this.CountryDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryDescriptionField, value) != true)) {
                    this.CountryDescriptionField = value;
                    this.RaisePropertyChanged("CountryDescription");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceCountries.StudentsServiceSoap")]
    public interface StudentsServiceSoap {
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément term de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStudentNames", ReplyAction="*")]
        WebServicesAJAX.ServiceReferenceCountries.GetStudentNamesResponse GetStudentNames(WebServicesAJAX.ServiceReferenceCountries.GetStudentNamesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStudentNames", ReplyAction="*")]
        System.Threading.Tasks.Task<WebServicesAJAX.ServiceReferenceCountries.GetStudentNamesResponse> GetStudentNamesAsync(WebServicesAJAX.ServiceReferenceCountries.GetStudentNamesRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément GetCountriesResult de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCountries", ReplyAction="*")]
        WebServicesAJAX.ServiceReferenceCountries.GetCountriesResponse GetCountries(WebServicesAJAX.ServiceReferenceCountries.GetCountriesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCountries", ReplyAction="*")]
        System.Threading.Tasks.Task<WebServicesAJAX.ServiceReferenceCountries.GetCountriesResponse> GetCountriesAsync(WebServicesAJAX.ServiceReferenceCountries.GetCountriesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStudentNamesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStudentNames", Namespace="http://tempuri.org/", Order=0)]
        public WebServicesAJAX.ServiceReferenceCountries.GetStudentNamesRequestBody Body;
        
        public GetStudentNamesRequest() {
        }
        
        public GetStudentNamesRequest(WebServicesAJAX.ServiceReferenceCountries.GetStudentNamesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetStudentNamesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string term;
        
        public GetStudentNamesRequestBody() {
        }
        
        public GetStudentNamesRequestBody(string term) {
            this.term = term;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStudentNamesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStudentNamesResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebServicesAJAX.ServiceReferenceCountries.GetStudentNamesResponseBody Body;
        
        public GetStudentNamesResponse() {
        }
        
        public GetStudentNamesResponse(WebServicesAJAX.ServiceReferenceCountries.GetStudentNamesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetStudentNamesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebServicesAJAX.ServiceReferenceCountries.ArrayOfString GetStudentNamesResult;
        
        public GetStudentNamesResponseBody() {
        }
        
        public GetStudentNamesResponseBody(WebServicesAJAX.ServiceReferenceCountries.ArrayOfString GetStudentNamesResult) {
            this.GetStudentNamesResult = GetStudentNamesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCountriesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCountries", Namespace="http://tempuri.org/", Order=0)]
        public WebServicesAJAX.ServiceReferenceCountries.GetCountriesRequestBody Body;
        
        public GetCountriesRequest() {
        }
        
        public GetCountriesRequest(WebServicesAJAX.ServiceReferenceCountries.GetCountriesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetCountriesRequestBody {
        
        public GetCountriesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCountriesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCountriesResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebServicesAJAX.ServiceReferenceCountries.GetCountriesResponseBody Body;
        
        public GetCountriesResponse() {
        }
        
        public GetCountriesResponse(WebServicesAJAX.ServiceReferenceCountries.GetCountriesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCountriesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebServicesAJAX.ServiceReferenceCountries.Country[] GetCountriesResult;
        
        public GetCountriesResponseBody() {
        }
        
        public GetCountriesResponseBody(WebServicesAJAX.ServiceReferenceCountries.Country[] GetCountriesResult) {
            this.GetCountriesResult = GetCountriesResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface StudentsServiceSoapChannel : WebServicesAJAX.ServiceReferenceCountries.StudentsServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StudentsServiceSoapClient : System.ServiceModel.ClientBase<WebServicesAJAX.ServiceReferenceCountries.StudentsServiceSoap>, WebServicesAJAX.ServiceReferenceCountries.StudentsServiceSoap {
        
        public StudentsServiceSoapClient() {
        }
        
        public StudentsServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StudentsServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StudentsServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StudentsServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServicesAJAX.ServiceReferenceCountries.GetStudentNamesResponse WebServicesAJAX.ServiceReferenceCountries.StudentsServiceSoap.GetStudentNames(WebServicesAJAX.ServiceReferenceCountries.GetStudentNamesRequest request) {
            return base.Channel.GetStudentNames(request);
        }
        
        public WebServicesAJAX.ServiceReferenceCountries.ArrayOfString GetStudentNames(string term) {
            WebServicesAJAX.ServiceReferenceCountries.GetStudentNamesRequest inValue = new WebServicesAJAX.ServiceReferenceCountries.GetStudentNamesRequest();
            inValue.Body = new WebServicesAJAX.ServiceReferenceCountries.GetStudentNamesRequestBody();
            inValue.Body.term = term;
            WebServicesAJAX.ServiceReferenceCountries.GetStudentNamesResponse retVal = ((WebServicesAJAX.ServiceReferenceCountries.StudentsServiceSoap)(this)).GetStudentNames(inValue);
            return retVal.Body.GetStudentNamesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebServicesAJAX.ServiceReferenceCountries.GetStudentNamesResponse> WebServicesAJAX.ServiceReferenceCountries.StudentsServiceSoap.GetStudentNamesAsync(WebServicesAJAX.ServiceReferenceCountries.GetStudentNamesRequest request) {
            return base.Channel.GetStudentNamesAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebServicesAJAX.ServiceReferenceCountries.GetStudentNamesResponse> GetStudentNamesAsync(string term) {
            WebServicesAJAX.ServiceReferenceCountries.GetStudentNamesRequest inValue = new WebServicesAJAX.ServiceReferenceCountries.GetStudentNamesRequest();
            inValue.Body = new WebServicesAJAX.ServiceReferenceCountries.GetStudentNamesRequestBody();
            inValue.Body.term = term;
            return ((WebServicesAJAX.ServiceReferenceCountries.StudentsServiceSoap)(this)).GetStudentNamesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServicesAJAX.ServiceReferenceCountries.GetCountriesResponse WebServicesAJAX.ServiceReferenceCountries.StudentsServiceSoap.GetCountries(WebServicesAJAX.ServiceReferenceCountries.GetCountriesRequest request) {
            return base.Channel.GetCountries(request);
        }
        
        public WebServicesAJAX.ServiceReferenceCountries.Country[] GetCountries() {
            WebServicesAJAX.ServiceReferenceCountries.GetCountriesRequest inValue = new WebServicesAJAX.ServiceReferenceCountries.GetCountriesRequest();
            inValue.Body = new WebServicesAJAX.ServiceReferenceCountries.GetCountriesRequestBody();
            WebServicesAJAX.ServiceReferenceCountries.GetCountriesResponse retVal = ((WebServicesAJAX.ServiceReferenceCountries.StudentsServiceSoap)(this)).GetCountries(inValue);
            return retVal.Body.GetCountriesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebServicesAJAX.ServiceReferenceCountries.GetCountriesResponse> WebServicesAJAX.ServiceReferenceCountries.StudentsServiceSoap.GetCountriesAsync(WebServicesAJAX.ServiceReferenceCountries.GetCountriesRequest request) {
            return base.Channel.GetCountriesAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebServicesAJAX.ServiceReferenceCountries.GetCountriesResponse> GetCountriesAsync() {
            WebServicesAJAX.ServiceReferenceCountries.GetCountriesRequest inValue = new WebServicesAJAX.ServiceReferenceCountries.GetCountriesRequest();
            inValue.Body = new WebServicesAJAX.ServiceReferenceCountries.GetCountriesRequestBody();
            return ((WebServicesAJAX.ServiceReferenceCountries.StudentsServiceSoap)(this)).GetCountriesAsync(inValue);
        }
    }
}
